---

language: java
jdk:
  - oraclejdk8

env:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: build
      install: ./gradlew setupCiWorkspace
      script: ./gradlew build

before_deploy:
  - 'export BODY=$(cat version.json | sed -nE "s/\\s*\"$(git tag --sort=-taggerdate | head -1 | cut -b 2-)\":\\s*\"(.*)\"\\s*,?\\s*/\1/p" | sed "s/\\\\n/\\n/g")'

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/libs/*
  body: $BODY
  on:
    tags: true
  skip_cleanup: true
