
modLoader='javafml'
loaderVersion='[25,)'
issueTrackerURL='https://github.com/necauqua/subpocket/issues'

[[mods]]
modId='subpocket'
version='${file.jarVersion}'
displayName='subpocket'
updateJSONURL='https://raw.githubusercontent.com/wiki/necauqua/subpocket/updates.json'
displayURL='https://www.curseforge.com/minecraft/mc-mods/subpocket'
logoFile='logo.png'
credits='People from my discord who keep me entertained and remind me to have an above-zero level of productivity'
authors='necauqua'
description='''
This mod adds almost for free some INFININE (omg) storage to the game.

Butt beware..
'''
