modLoader = 'javafml'
loaderVersion = '[41,)'
license = 'MIT'
issueTrackerURL = 'https://github.com/necauqua/subpocket/issues'

[[mods]]
modId = 'subpocket'
version = '${file.jarVersion}'
displayName = 'subpocket'
updateJSONURL = 'https://raw.githubusercontent.com/wiki/necauqua/subpocket/updates.json'
displayURL = 'https://modrinth.com/mod/subpocket'
logoFile = 'logo.png'
credits = '''
People from my discord who keep me entertained and remind me to have an above-zero level of productivity

__Minecraftian__ - for the cool subpocket key texture
'''
authors = 'necauqua'
description = '''
This mod adds almost for free some INFININE (omg) storage to the game.

Butt beware..
'''
[[dependencies.subpocket]]
modId = 'forge'
mandatory = true
versionRange = '[41,)'
ordering = 'NONE'
side = 'BOTH'
[[dependencies.subpocket]]
modId = 'minecraft'
mandatory = true
versionRange = '[1.19,1.20)'
ordering = 'NONE'
side = 'BOTH'
