name: Update Changelog
on:
  push:
    branches:
      - main
jobs:
  update-changelogs:
    name: Update changelogs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout the wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Generate a human changelog
        shell: bash
        run: ./gradlew -q generateChangelog --template .github/workflows/changelog-template.md > wiki/Changelog.md

      - name: Generate Forge updates.json
        shell: bash
        run: ./gradlew -q generateForgeUpdates --template .github/workflows/updates-template.json > wiki/updates.json

      - name: Push to wiki
        run: |
          cd wiki
          git config --local user.email action@github.com
          git config --local user.name 'Changelog Updater'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update changelog'
          git push
