name: Push to main
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.gradle'
jobs:
  mcmod-workflow:
    uses: necauqua/mcmod-workflow/.github/workflows/push-to-main.yml@main
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
