name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set the keystore and gradle properties
        shell: bash
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p $HOME/.gradle
          echo "$KEYSTORE" | base64 -d > $HOME/.gradle/keystore.jks
          echo "$GRADLE_PROPERTIES" | base64 -d | sed "s:\$HOME:$HOME:g" > $HOME/.gradle/gradle.properties

      - name: Check if this is a tag
        id: tag-check
        run: git describe --exact-match HEAD && echo '::set-output name=TAGGED::1' || true

      - name: Make a release build and push it to curse, github and maven
        run: ./gradlew publish githubRelease curseforge
        if: steps.tag-check.outputs.TAGGED

      - name: Make a git build and push it to curse
        run: ./gradlew curseforge
        if: '!steps.tag-check.outputs.TAGGED'
